### PR TITLE
Fixed Build

### LINKED ISSUE #102: Drop OracleJDK support?
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filled: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aidealista
    * Checked that there is not already provided the described functionality

### Description

Should support for OracleJDK be dropped? I've been trying to debug the new updated OracleJDK urls, it requires registering a developer account, and using a limited time auth token in the URL to download. In theory I could add an Ansible step to login with my Oracle developer credentials, and grep the auth token from the HTTP response...

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

### PR DESCRIPTION
**Pull request by apolloclark**
# Description of the Change

This PR fixes #102 and a few other things:
- removed Oracle JDK tests in travis.yml 
- updated Debian 9 Stretch, Ubuntu 16.04 Xenial, and Ubuntu 18.04 Bionic, repo versions
- added testing for CentOS 7, RHEL 7, RHEL 8, and Debian 10 Buster

### Benefits

Everything works.

### Possible Drawbacks

None.

### Applicable Issues

None.

### CODE REVIEW

**Comment by apolloclark** [comment]
@jnogol any feedback?

**Comment by apolloclark** [comment]
I fixed the tests to allow the use of "11.x" or "8.x" versioning.

On CentOS / RHEL, I had the Ansible task set to install the latest "java-11-openjdk-headless" version, and later check what specific version was installed, used to set the "alternative" program name, but Molecule would complain of idempotency errors. This is not an issue on Ubuntu, nor Debian. I fixed it by hard-coding the latest CentOS version string, which is hackish, but does work. Thought?

**Comment by apolloclark** [comment]
updates for CentOS 7.6 and Debian Stretch

**Comment by apolloclark** [comment]
Thoughts?

**Comment by frantsao** [comment]
Thanks for your patches, @apolloclark . We fixed this recurring problem in the release 5.1.0, where we install by default the last package available for the selected major release (but you still can fix the package version if you need it).

**Pull request closed without merging**
